### ISSUE TITLE
7.00 Bugs and Todo's

### ISSUE THREAD

**Issue by dun1007** [dun1007/fateanother#112]
**Bugs**

- npc_abilities_override.txt file is bugged; it is causing sticky slot to be disabled and making console spam "Attempt to add unknown item to stock info" every frame. Removing it resolves the issue, but there is no other way known to prohibit purchase of default Dota 2 items.
- multiteam_flyout_scoreboard does not appear after pressing button.
- New Panorama item shop does not have keybind(1-9 to purcahse item)
- Hero stats are not showing even when Alt key is pressed. Still unsure if it is exclusive issue for fate.
- Disconnecting from game crashes client. This includes reloading the game(which disconnects you from your current game) in test client.
- Performing arithmetic in KV does not work. Perhaps it is intended by Valve

**Todo**

- [x] Since we are no longer using Scaleform for hero pick phase, hero portraits and animation cards are now using assets from panorama directory. They need to be located and replaced by fate assets.(GCFScape plz) 
- [x] Fix the position and proportion of custom UI to fit brand new HUD
- [x] Disable Talent tree
- [x] Add Attribute(all stats+2) back
- [ ] Fix alt-click buff feature
- [ ] Create new message window above minimap and migrate printouts that were previously handled by GameRules:SendCustomMessage, since chat window is way too saturated after patch
- [x] Fix flyout scoreboard not working
- [x] Fix item slot transfer issue that was brought forth with addition of backpack
- [x] Make scoreboard and hero pick UI show 6th player
- [x] Flush all Talents at the beginning of game(override ability 10-17)
- [x] Investigate item purchase issue and backpack interaction
- [x] Prevent item purchase at the pick phase screen
- [x] Make sure no ability contains arithmetic in KV

**Comment by xRainZx** [comment]
Volvo pls

**Comment by xRainZx** [comment]
RIP shop keybind.

**Comment by dun1007** [comment]
Portrait card requires .webm file now

Sticky purchase slot is still bugged

**Comment by sngweicong** [comment]
Hero does not gain ability points when leveling to 17 19 21 22 23 24.

"AbilityLayout"				"6" 
in npc_heroes_custom.txt appears to not work and the size is not fixed now; Un-hiding abilities will result in a larger ability skill bar.

**Comment by MiguelValentine** [comment]
osx can't download DOTA2 DEVELOP TOOL,(= w =).Go ahead!

**Comment by OniCHICHIfather** [comment]
Just stating the bug i found.. TA's ambush seems like not doing any damage, Red Pot and Mana Essence can't be used, when shopping with not enough money the rest of the items in toolsbox will dissapear, sometimes the slot of toolsbox bugged and only 2 of them will work to shop.

**Comment by dun1007** [comment]
4857e18 should address most of UI and backpack issues

Sticky slot still bugged. items.txt isn't any better than abilities_override.txt 

Need real 6v6 match to test item entity saturation. Did not have issues solo
